name: SendEmail_build_test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.Exchange.SendEmail/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.Exchange.SendEmail
      env_var_name_1: Exchange_CredBase64_Part1
      env_var_name_2: Exchange_CredBase64_Part2
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.Exchange_CREDBASE64_PART1 }}
      env_var_value_2: ${{ secrets.Exchange_CREDBASE64_PART2 }}